// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Returns the service liveness status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Returns the service readiness status including dependency checks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/operations": {
            "get": {
                "description": "Returns a paginated list of operations. Status reads are authoritative MariaDB reads.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "List operations",
                "parameters": [
                    {
                        "type": "string",
                        "example": "QUEUED",
                        "description": "Filter by operation status (e.g. QUEUED, COMPLETED)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "image-processor",
                        "description": "Filter by processor name",
                        "name": "processor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "cursor-abc",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 20,
                        "description": "Page size (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ListOperationsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates the durable operation row and initial append-only event. Does not schedule work before the input upload is complete.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Create an operation",
                "parameters": [
                    {
                        "type": "string",
                        "example": "ops-create-001",
                        "description": "Idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create operation request",
                        "name": "createOperationRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_operation.CreateOperationRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.CreateOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operations/{id}": {
            "get": {
                "description": "Status reads are authoritative MariaDB reads served by an entry-capable instance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Read operation status",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"1\"",
                        "description": "ETag for conditional request",
                        "name": "If-None-Match",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "op-abc123",
                        "description": "Operation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.OperationResponse"
                        }
                    },
                    "304": {
                        "description": "Not Modified",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.OperationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operations/{id}/cancel": {
            "post": {
                "description": "Cancellation is an idempotent intent. Persists cancel_requested_at and emits an event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Cancel an operation",
                "parameters": [
                    {
                        "type": "string",
                        "example": "ops-cancel-001",
                        "description": "Idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2\"",
                        "description": "Operation version precondition",
                        "name": "If-Match",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "op-abc123",
                        "description": "Operation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation reason",
                        "name": "cancelRequest",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.CancelOperationInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.CancelOperationResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.CancelOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Precondition Failed",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operations/{id}/file": {
            "put": {
                "description": "The client streams bytes to the entry upload endpoint. The entry streams them to a node-local ingress file, enforces size limits, computes SHA-256 incrementally, and records the file metadata. Supports raw binary body (application/octet-stream) or multipart form data with a \"file\" field.",
                "consumes": [
                    "multipart/form-data",
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Stream the input file",
                "parameters": [
                    {
                        "type": "string",
                        "example": "ops-file-001",
                        "description": "Idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1\"",
                        "description": "Operation version precondition",
                        "name": "If-Match",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "example": 1048576,
                        "description": "Optional, must match bytes received",
                        "name": "Content-Length",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "sha256=abc123...",
                        "description": "SHA-256 digest of request body",
                        "name": "Digest",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "example": 1048576,
                        "description": "Declared byte count",
                        "name": "X-File-Size",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "image.png",
                        "description": "Client filename metadata",
                        "name": "X-File-Name",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "op-abc123",
                        "description": "Operation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.FileOperationResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.FileOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Precondition Failed",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operations/{id}/result": {
            "get": {
                "description": "Returns the single structured result for a completed operation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Retrieve a result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ResultResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/operations/{id}/retry": {
            "post": {
                "description": "Retry is allowed only from FAILED or TIMEOUT, subject to budget and policy.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Retry an operation",
                "parameters": [
                    {
                        "type": "string",
                        "example": "ops-retry-001",
                        "description": "Idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2\"",
                        "description": "Operation version precondition",
                        "name": "If-Match",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "op-abc123",
                        "description": "Operation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Retry reason",
                        "name": "retryRequest",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.RetryOperationInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.RetryOperationResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.RetryOperationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Precondition Failed",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_operation.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "internal_operation.CancelOperationInput": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "internal_operation.CancelOperationResponse": {
            "type": "object",
            "properties": {
                "cancel_requested_at": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_url": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.CreateOperationRequest": {
            "type": "object",
            "required": [
                "processor"
            ],
            "properties": {
                "client_reference": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "options": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "processor": {
                    "type": "string"
                },
                "retry_policy": {
                    "$ref": "#/definitions/internal_operation.RetryPolicyReq"
                }
            }
        },
        "internal_operation.CreateOperationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "string"
                },
                "result_url": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_url": {
                    "type": "string"
                },
                "upload_target": {
                    "$ref": "#/definitions/internal_operation.UploadTarget"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_operation.ErrorDetailItem"
                    }
                },
                "message": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "retryable": {
                    "type": "boolean"
                }
            }
        },
        "internal_operation.ErrorDetailItem": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "internal_operation.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_operation.ErrorDetail"
                }
            }
        },
        "internal_operation.FileOperationResponse": {
            "type": "object",
            "properties": {
                "input_file": {
                    "$ref": "#/definitions/internal_operation.InputFile"
                },
                "operation_id": {
                    "type": "string"
                },
                "result_url": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.InputFile": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.ListOperationsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_operation.OperationItem"
                    }
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "internal_operation.OperationError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_operation.OperationItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "max_attempts": {
                    "type": "integer"
                },
                "operation_id": {
                    "type": "string"
                },
                "processor": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.OperationResponse": {
            "type": "object",
            "properties": {
                "cancel_requested_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_attempt_id": {
                    "type": "string"
                },
                "current_job_id": {
                    "type": "string"
                },
                "current_transfer_id": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "error": {
                    "$ref": "#/definitions/internal_operation.OperationError"
                },
                "input_file": {
                    "$ref": "#/definitions/internal_operation.InputFile"
                },
                "max_attempts": {
                    "type": "integer"
                },
                "operation_id": {
                    "type": "string"
                },
                "processor": {
                    "type": "string"
                },
                "result_url": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.ResultResponse": {
            "type": "object",
            "properties": {
                "operation_id": {
                    "type": "string"
                },
                "processor": {
                    "type": "string"
                },
                "produced_at": {
                    "type": "string"
                },
                "result_id": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "integer"
                },
                "value": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "internal_operation.RetryOperationInput": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "internal_operation.RetryOperationResponse": {
            "type": "object",
            "properties": {
                "current_attempt_id": {
                    "type": "string"
                },
                "current_job_id": {
                    "type": "string"
                },
                "max_attempts": {
                    "type": "integer"
                },
                "operation_id": {
                    "type": "string"
                },
                "retry_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "status_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.RetryPolicyReq": {
            "type": "object",
            "properties": {
                "max_attempts": {
                    "type": "integer"
                }
            }
        },
        "internal_operation.UploadTarget": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "max_bytes": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authorization": {
            "description": "Type \"Bearer \u003ctoken\u003e\" or \"Basic \u003ccredentials\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "Idempotency-Key": {
            "description": "Required for create, upload, cancel, and retry requests",
            "type": "apiKey",
            "name": "Idempotency-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "File Processing Service API",
	Description:      "HTTP API for file upload, processing orchestration, and result retrieval",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
